Implement loader for Fennel
lunarmodules/busted pull request #740
Opened 2024-03-09 19:24 UTC by HiPhish

Closes #738

Tests can be written in Fennel if `fennel` is among the loaders. Currently the traceback is wrong for failures and pending tests, but it is wrong for tests written in Moonscript as well, so this seems to be a general problem with busted.

It would have been cool if we could make `it`, `describe` and so on into macros to not have to manually wrap the test body inside a thunk every time.

```fennel
;; With macro
(it "Adds two numbers"
  (assert.are.equal 5 (+ 2 3)))

;; Without macro
(it "Adds two numbers"
  (fn []
    (assert.are.equal 5 (+ 2 3))))
```

This macro can accomplish it when added to the beginning of a test:

```fennel
(macro it [description & body]
  `(let [fenv# (or (and getfenv (getfenv)) _ENV)]
     ((. fenv# :it) ,description
                (fn [] ,(unpack body)))))
```

However, the source map produces rather weird mappings from Lua to Fennel (it maps the assertion to the body of the macro definition), so for now I won't pursue this.

2024-03-09 19:35 UTC, alerque requested changes
At first blush this looks like it's going to be fine. I don't have any Fennel expertise but it isn't like this is going to break anything *else*, and I don't expect any real reason to not include such a module if Fennel folks say it is useful.

I'll review details later this week (feel free to poke again if this falls off my radar), but to quick things:

1. I've been roughly following the [conventional commit spec](https://www.conventionalcommits.org/en/v1.0.0/), so this commit message should be `feat(core): Implement loader for Fennel` or something like that.
2. We should probably add a test. Somehow...obviously we're going to have a dependency problem with that but we can fix that in CI and maybe make it an optional test for local testing for folks that don't have Fennel setup. Is their prior art for testing our other loaders?

2024-03-10 10:08 UTC, HiPhish commented
Thank you for your response. I have amended the commit message.

> We should probably add a test.

Maybe I am missing something here, but it does not look like there are any loader tests.  There is the file `spec/modules/file_loader_spec.lua`, but all it does is require and call a module, but it does not do anything with the results.

> and maybe make it an optional test for local testing for folks that don't have Fennel setup.

That's simple enough, we can `pcall(require, 'fennel')` in the test; if the call errors then Fennel is not available and we can skip the Fennel loader.

> I don't have any Fennel expertise

[Fennel](https://fennel-lang.org/) is pretty much just Lua with Lisp notation (some special forms plus a macro system), so it maps very closely to Lua.

2024-03-18 23:42 UTC, HiPhish commented
> feel free to poke again if this falls off my radar

*poke* @alerque

2024-07-12 19:51 UTC, offsetcyan commented
poke @alerque

2024-08-04 12:13 UTC, emmabukacek commented
Poke @alerque 🐸

2024-10-18 01:32 UTC, noncom commented
poke @alerque 😄

2024-10-22 13:36 UTC, alerque approved these changes

2024-10-22 13:38 UTC, merged

2024-10-23 14:56 UTC, noncom commented
❤️